services:
  # 后端 API 服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-todo-backend-prod
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PYTHONPATH=/app
      # DATABASE_PATH=/app/data/tasks.db  # 已删除 data 目录，使用 PostgreSQL
    volumes:
      # 已删除 data 目录，使用 PostgreSQL 数据库
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:3000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # 前端 React 应用 (生产模式)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: ai-todo-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
